package com.myspace.ng_oft;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BPMSvcPdtWantsDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String productFamily;
	private java.lang.String actionCode;

	public BPMSvcPdtWantsDO() {
	}

	public java.lang.String getProductFamily() {
		return this.productFamily;
	}

	public void setProductFamily(java.lang.String productFamily) {
		this.productFamily = productFamily;
	}

	public java.lang.String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(java.lang.String actionCode) {
		this.actionCode = actionCode;
	}

	public BPMSvcPdtWantsDO(java.lang.String productFamily,
			java.lang.String actionCode) {
		this.productFamily = productFamily;
		this.actionCode = actionCode;
	}

}