package com.myspace.ng_oft;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RLCustomer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Age")
	private java.lang.Integer age;

	private java.lang.String customerId;

	private java.lang.String message;

	public RLCustomer() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public RLCustomer(java.lang.Integer age, java.lang.String customerId,
			java.lang.String message) {
		this.age = age;
		this.customerId = customerId;
		this.message = message;
	}

}