package com.myspace.ng_oft;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RLSvcInst implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.myspace.ng_oft.BPMSvcInstWantsDO wants;

	public RLSvcInst() {
	}

	public com.myspace.ng_oft.BPMSvcInstWantsDO getWants() {
		return this.wants;
	}

	public void setWants(com.myspace.ng_oft.BPMSvcInstWantsDO wants) {
		this.wants = wants;
	}

	public RLSvcInst(com.myspace.ng_oft.BPMSvcInstWantsDO wants) {
		this.wants = wants;
	}

}